import { useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowRight, FolderClosed, ShieldCheck, UsersRound, Eye, LoaderCircle, LockKeyhole } from 'lucide-react';
import { request } from '../api';
import type { User } from '../types';
import { ErrorMessage, Logo } from './UI';
export default function Login({ onLogin, onPreview }: { onLogin: (user: User) => void; onPreview: () => void }) {
  const [email, setEmail] = useState('finance@demo.local'); const [password, setPassword] = useState('Demo123!');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request<{ token: string; user: User }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); sessionStorage.setItem('atlas-token', data.token); onLogin(data.user); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="login-page"><div className="login-story"><Logo /><div className="login-story-content"><span className="eyebrow">A PLACE FOR YOUR TEAM'S WORK</span><h1>Good work starts<br />with a little order.</h1><p>A thoughtful home for your documents.<br />Organize effortlessly. Share with confidence.</p><div className="login-illustration"><div className="illustration-folder"><FolderClosed size={46} strokeWidth={1.3} /><div><strong>Your next great project</strong><span>Everything in the right place</span></div><span className="illustration-check">✓</span></div><div className="illustration-row"><span className="illustration-file">PDF</span><span>Quarterly report</span><ShieldCheck size={18} /></div><div className="illustration-row"><span className="illustration-file green">XLS</span><span>Team budget</span><UsersRound size={18} /></div></div><div className="login-benefits"><span><ShieldCheck size={16} />Permission-based sharing</span><span><FolderClosed size={16} />One organized workspace</span></div></div><span className="login-story-footer">ATLAS WORKSPACE <span>Less searching. More doing.</span></span></div>
    <main className="login-main"><span className="local-label"><span />LOCAL DEMO</span><div className="login-form-wrap"><span className="login-icon"><LockKeyhole size={24} /></span><h2>Welcome to your workspace</h2><p>Sign in to bring your documents together.</p><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="username" required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required /></label><ErrorMessage message={error} /><button className="button primary login-submit" disabled={busy}>{busy ? <LoaderCircle size={17} className="spin" /> : <>Sign in<ArrowRight size={17} /></>}</button></form><div className="demo-accounts"><span className="eyebrow">TRY A DEMO ACCOUNT</span><div>{['finance', 'manager', 'employee', 'admin'].map(x => <button key={x} onClick={() => { setEmail(`${x}@demo.local`); setPassword('Demo123!'); setError(''); }} className={email.startsWith(x + '@') ? 'active' : ''}>{x.charAt(0).toUpperCase() + x.slice(1)}</button>)}</div><p>All demo accounts use <code>Demo123!</code></p></div><button className="preview-link" onClick={onPreview}><Eye size={16} />Explore the interface<ArrowRight size={14} /></button><p className="preview-caption">A read-only preview. No sign-in needed.</p></div><span className="login-footer"><ShieldCheck size={14} />Your files. Your team. Your control.</span></main></div>;
}
