import { useEffect, useState } from 'react';
import { ChevronRight, Folder, LoaderCircle } from 'lucide-react';
import { request, resourcePath } from '../api';
import type { Explorer, Resource } from '../types';
import { ErrorMessage, Modal } from './UI';
export default function MoveDialog({ resource, onClose, onChange }: { resource: Resource; onClose: () => void; onChange: () => void }) {
  const [folder, setFolder] = useState<string | null>(null); const [data, setData] = useState<Explorer | null>(null); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { let active = true; setLoading(true); request<Explorer>(`/explorer?view=files${folder ? `&folderId=${folder}` : ''}`).then(x => { if (active) { setData(x); setError(''); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [folder]);
  async function move() { if (!data?.folderId) return; setBusy(true); setError(''); try { await request(`${resourcePath(resource)}/move`, { method: 'PATCH', body: JSON.stringify({ parentFolderId: data.folderId }) }); onChange(); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title={`Move “${resource.name}”`} subtitle="Choose a destination in your workspace." onClose={onClose}><div className="move-content"><div className="breadcrumbs">{data?.breadcrumbs.map(c => <button key={c.id} onClick={() => setFolder(c.id)}>{c.name}<ChevronRight size={13} /></button>)}</div><div className="folder-picker">{loading ? <LoaderCircle className="spin" /> : data?.items.filter(x => x.type === 'folder' && x.id !== resource.id).map(x => <button key={x.id} onClick={() => setFolder(x.id)}><Folder size={21} />{x.name}<ChevronRight size={16} /></button>)}{!loading && !data?.items.some(x => x.type === 'folder' && x.id !== resource.id) && <p>No subfolders. You can move this item here.</p>}</div><div className="notice">Moving an item changes its inherited permissions. Direct shares stay attached.</div><ErrorMessage message={error} /></div><div className="modal-footer"><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" onClick={move} disabled={busy || loading || !data?.folderId || data.folderId === resource.parentFolderId}>{busy && <LoaderCircle size={16} className="spin" />}Move here</button></div></Modal>;
}
