import { useEffect, useState } from 'react';
import { Link2, LoaderCircle, ShieldCheck, Trash2, UsersRound } from 'lucide-react';
import { request, resourcePath } from '../api';
import type { Resource, Share, User } from '../types';
import { has, READ, WRITE, DELETE, SHARE } from '../types';
import { Avatar, ErrorMessage, FileIcon, Modal } from './UI';
export default function ShareDialog({ resource, users, currentUser, preview, onClose, onChange }: { resource: Resource; users: User[]; currentUser: User; preview: boolean; onClose: () => void; onChange: () => void }) {
  const [shares, setShares] = useState(resource.sharedWith); const [recipient, setRecipient] = useState(''); const [bits, setBits] = useState(READ);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const canShare = has(resource.permissions, SHARE) && !preview;
  useEffect(() => { let active = true; if (!preview) request<Share[]>(`${resourcePath(resource)}/shares`).then(s => { if (active) setShares(s); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [resource, preview]);
  const choose = (id: string) => { setRecipient(id); setBits(shares.find(x => x.userId === id)?.permissions ?? READ); setError(''); };
  async function refresh() { setShares(await request<Share[]>(`${resourcePath(resource)}/shares`)); onChange(); }
  async function save() { setBusy(true); setError(''); try { await request(`${resourcePath(resource)}/shares`, { method: 'PUT', body: JSON.stringify({ userId: recipient, permissions: bits }) }); await refresh(); setRecipient(''); setBits(READ); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function remove(id: string) { setBusy(true); setError(''); try { await request(`${resourcePath(resource)}/shares/${id}`, { method: 'DELETE' }); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const existing = shares.find(s => s.userId === recipient);
  return <Modal title="Share with your team" subtitle="Give the right people the right access." onClose={onClose} wide><div className="shared-resource"><FileIcon resource={resource} /><div><strong>{resource.name}</strong><span>{resource.type === 'folder' ? 'Folder · Access is inherited by its contents' : 'File · Access applies to this document'}</span></div><ShieldCheck size={20} /></div>
    {preview && <div className="notice">Preview mode · Sharing changes are available after sign-in.</div>}
    <div className="share-form"><label>Share with<select value={recipient} onChange={e => choose(e.target.value)} disabled={!canShare || busy}><option value="">Select a teammate</option>{users.filter(u => u.id !== resource.ownerId && u.id !== currentUser.id).map(u => <option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label><span className="field-label">Permissions</span><div className="permission-options">{[{ bit: READ, label: 'Read', detail: 'View & download' }, { bit: WRITE, label: 'Write', detail: 'Upload & edit' }, { bit: DELETE, label: 'Delete', detail: 'Remove items' }, { bit: SHARE, label: 'Share', detail: 'Manage access' }].map(p => <label key={p.bit} className={has(bits, p.bit) ? 'checked' : ''}><input type="checkbox" checked={has(bits, p.bit)} disabled={!canShare || busy || !has(resource.permissions, p.bit)} onChange={e => setBits(p.bit === READ && !e.target.checked ? 0 : e.target.checked ? bits | p.bit | READ : bits & ~p.bit)} /><strong>{p.label}</strong><span>{p.detail}</span></label>)}</div>
      <div className="share-form-bottom"><p>{bits === 0 ? 'No permissions blocks inherited access here.' : existing?.inherited ? `This will override access inherited from ${existing.source}.` : 'Only selected teammates can access this item.'}</p><button className="button primary" disabled={!recipient || !canShare || busy} onClick={save}>{busy ? <LoaderCircle size={16} className="spin" /> : <UsersRound size={16} />}{bits === 0 ? 'Block access' : existing ? 'Update access' : 'Grant access'}</button></div></div>
    <ErrorMessage message={error} /><div className="access-section"><h3>People with access <span>{shares.filter(s => s.permissions > 0).length + 1}</span></h3><div className="access-row"><Avatar name={resource.owner} /><div className="access-person"><strong>{resource.owner}{resource.ownerId === currentUser.id ? ' (you)' : ''}</strong><span>{resource.ownerEmail}</span></div><span className="owner-label">Owner</span></div>{shares.map(s => <div className="access-row" key={s.userId}><Avatar name={s.name} index={1} /><div className="access-person"><strong>{s.name}</strong><span>{s.email}</span>{s.inherited && <small><Link2 size={11} />Inherited from {s.source}</small>}</div><button className="access-label" onClick={() => choose(s.userId)} disabled={!canShare || busy} title="Edit this person's permissions">{s.permissions === 0 ? 'Blocked' : [READ, WRITE, DELETE, SHARE].filter(b => has(s.permissions, b)).map(b => ({ 1: 'Read', 2: 'Write', 4: 'Delete', 8: 'Share' })[b]).join(', ')}</button>{!s.inherited && canShare && <button className="icon-button danger-text" onClick={() => remove(s.userId)} disabled={busy} aria-label={`Remove direct access for ${s.name}`} title="Remove direct grant; inherited access will apply"><Trash2 size={15} /></button>}</div>)}</div><div className="modal-footer"><span><ShieldCheck size={14} />{resource.type === 'folder' ? 'Child permissions can override this access.' : 'Private by default. Shared by choice.'}</span><button className="button secondary" onClick={onClose}>Done</button></div></Modal>;
}
